node {
   stage('Git checkout') {
      git 'https://github.com/s-atkinson/twitter-api.git'
   }
   stage('Common') {
        try {
            sh "mvn clean verify -Dtags='type:common'"
        } catch (err) {
   }
   stage('Twitter') {
        try {
            sh "mvn clean verify -Dtags='type:twitter'"
        } catch (err) {
   }
   stage('Results') {
      junit '**/target/failsafe-reports/*.xml'
   }
}