pipeline {
   stage('Git checkout') {
      git 'https://github.com/s-atkinson/twitter-api.git'
   }
   stage('Common') {
        steps {
            Common: {
            sh "mvn clean verify -Dcucumber.options=\"--tags @common"
         }
   }
   stage('Twitter') {
        Twitter: {
             sh "mvn clean verify -Dcucumber.options=\"--tags @common"
         }
   }
   stage('Results') {
      junit '**/target/failsafe-reports/*.xml'
   }
}